### ISSUE TITLE
ec_preprocess03B: x_list 存在乱序问题

### ISSUE THREAD

**Issue by 6yq** [air391/calibration_process#2]
`python3 -m grid_calibration.process03B.ec_preprocess x list` 显示的 x_list 顺序并不是固定的，因此会造成 `... x run {n}` 时的 {n} 号文件并不一定和前一次查看 list 时的 {n} 号一样，导致单个 x 射线数据文件测试失效。

[P.S.] src_list 并没有这个问题

**Comment by air391** [comment]
测试了一下，03B的确存在该问题，其原因在于EC_operation_03B中x_list的定义方式
```python
        self.x_ch = [f for f in os.listdir(self.x_path) if '_rundata' in f and 'CI' not in f]
        self.x_list = list(set([f.split('_')[1] for f in self.x_ch]))
```
可以看到使用了set进行去重的工作，在此过程中使得两次初始化x_list的顺序不同，可以考虑使用其他方式去重，或者再对x_list进行排序

**Comment by 6yq** [comment]
对的，`os.listdir()` 应该遵循了数据文件固有的排序顺序，所以应该 05 没问题，03 的再使用 `sorted()` 就可以了
